language: r
cache: packages
dist: xenial
warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:cran/jq'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
    - libudunits2-dev
    - libprotoc-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - netcdf-bin

r_packages:
  - covr
  - xml2

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never

env:
  - TEST_DPLYR_INTERFACE=TRUE
