on: push

name: ckan-spin-up

jobs:
  ckan-spin-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone ckan docker repo
        run: |
          git config --global user.email "myrmecocystus@gmail.com"
          git config --global user.name "myrmecocystus"
          git clone https://github.com/okfn/docker-ckan.git
      - name: Spin up ckan
        run: |
          cd docker-ckan
          cp .env.example .env
          docker-compose build
          docker-compose up -d
